pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/password/', views.password_change, name='password_change'),
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('<int:user_pk>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField('self', symmetrical=False, related_name='followings')
    image = ProcessedImageField(blank=True,
                                processors=[Thumbnail(150, 150)],
                                format='png',
                                options={'quality': 100},
                                upload_to='%Y/%m/%d')
    selfpr = models.CharField(max_length=100)
    nickname = models.CharField(max_length=20)

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class CustomUserChangeForm(UserChangeForm):
    selfpr = forms.CharField(
        label = "자기소개",
        widget=forms.TextInput(attrs={
            'class': 'my-content form-control',
            'placeholder': '자기소개를 입력해주세요',
            'maxlength' : 300,
        })
    )

    class Meta:
        model = get_user_model()
        fields = ['email', 'nickname', 'image', 'selfpr']

class CustomUserCreationForm(UserCreationForm):
    selfpr = forms.CharField(
        label = "자기소개",
        widget=forms.TextInput(attrs={
            'class': 'my-content form-control',
            'placeholder': '자기소개를 입력해주세요',
            'maxlength' : 300,
        })
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email', 'nickname', 'image', 'selfpr')

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_GET

from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.http import JsonResponse

# Create your views here.
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect ('movies:index')

    else: 
        form = CustomUserCreationForm
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')

    else:
        form = AuthenticationForm()
    context = {
        'form' : form, 
    }
    return render(request, 'accounts/login.html', context)


@require_GET
def logout(request):
    auth_logout(request)
    return redirect('movies:index')


@require_http_methods(['GET', 'POST'])
def update(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', user.pk)
    
    else:
        form = CustomUserChangeForm(instance=user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@require_http_methods(['GET', 'POST'])
def password_change(request, user_pk):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            return redirect('accounts:update', request.user.pk)
    else:
        form = PasswordChangeForm(request.user)
    context ={
        'form': form,
    }
    return render(request, 'accounts/password_change.html', context)


@require_POST
def delete(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    user.delete()
    return redirect('movies:index')


@require_GET
def profile(request, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        user = request.user
        if person != user:
            if person.followers.filter(pk=user.pk).exists():
                person.followers.remove(user)
                follow = False
            else:
                person.followers.add(user)
                follow = True
            context = {
                'follow': follow,
                'followings_cnt': person.followings.count(),
                'followers_cnt': person.followers.count(),
            }
            return JsonResponse(context)
    return redirect('accounts:profile', person.username)

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/templates/accounts/_follow.html
<div>
  <hr>
  {% with followings=person.followings.all followers=person.followers.all %}
    <p id="follow-count" class="lead">
      팔로잉 : {{ followings|length }} / 팔로워 : {{ followers|length }}
    </p>
    <!-- 팔로우 버튼 -->
    {% if request.user != person %}
      <form id="follow-form" data-user-pk="{{ person.pk }}">
        {% csrf_token %}
        {% if request.user in followers %}
          <button id="follow-btn" class="btn-secondary btn-lg" role="button">Unfollow</button>
        {% else %}
          <button id="follow-btn" class="btn-primary btn-lg" role="button">Follow</button>
        {% endif %}
      </form>
    {% endif %}
  {% endwith %}
</div>
{% block script %}
  <script>
    const followForm = document.querySelector('#follow-form')
    // console.log(followForm)
    followForm.addEventListener('submit', function (event) {
      event.preventDefault()
      // console.log(event.target)
      const userPk = event.target.dataset.userPk
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
      // console.log(userPk, csrftoken)
      const headers = {
        headers: {
          'X-CSRFToken': csrftoken
        }
      }
      axios.post(`/accounts/follow/${userPk}/`, {}, headers)
      .then(function (res) {
        // console.log(res.data)
        const follow = res.data.follow
        const followers_cnt = res.data.followers_cnt
        const followings_cnt = res.data.followings_cnt
        // console.log(follow,followers_cnt, followings_cnt)

        const followBtn = document.querySelector('#follow-btn')
        if (follow) {
          followBtn.classList.add('btn-secondary')
          followBtn.classList.remove('btn-primary')
          followBtn.innerText = 'Unfollow'
        } else {
          followBtn.classList.add('btn-primary')
          followBtn.classList.remove('btn-secondary')
          followBtn.innerText = 'Follow'
        }

        const followCount = document.querySelector('#follow-count')
        followCount.innerText = `팔로잉 : ${followings_cnt} / 팔로워 : ${followers_cnt}`
      })
      .catch(function (err) {
        console.error(err)
      })
    })
  </script>
{% endblock script %}

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block content %}
accounts
{% endblock  %}

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
  <form action="" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit">
        제출
      </button>
    {% endbuttons %}
  </form>
{% endblock %}

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
  <form action="" method="POST" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit">
        제출
      </button>
    {% endbuttons %}
  </form>
{% endblock %}

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="media">
    {% if person.image %}
      <img src="{{ person.image.url }}" alt="{{ person.image }}" class="align-self-center mr-3 rounded-circle border border-warning mt-4">
    {% else %}
      <img width=150px height=150px src="{% static 'accounts/profile.png' %}" class="align-self-center mr-3 rounded-circle border border-warning mt-4" alt="profile">
    {% endif %}
    <div class="media-body">
      <h1 class="mt-4">{{ person.username }}</h1> 
      <p class="mb-0">{{ person.selfpr }}</p>
      <p>{% include 'accounts/_follow.html' %}</p>
    </div>
  </div>
  <p class="mt-3 ml-4"><a href="{% url 'accounts:update' person.pk %}">회원정보수정</a></p>
  <hr>
  <ul class="list-group">
    <li class="list-group-item list-group-item-info">{{ person.username }}이 작성한 리뷰</li>
    {% for review in person.reviewarticle_set.all %}
      <li class="list-group-item"><p class="my-2"><a href="{% url 'articles:review_detail' review.pk %}" class="badge badge-success">바로가기</a>&ensp;&ensp;{{ review.title }}</p></li>
    {% endfor %}
  </ul>
  <hr>
  <ul class="list-group">
    <li class="list-group-item list-group-item-info">{{ person.username }}이 작성한 리뷰 댓글</li>
    {% for review_comment in person.reviewcomment_set.all %}
      <li class="list-group-item"><p class="my-2"><a href="{% url 'articles:review_detail' review_comment.review_article.pk %}" class="badge badge-success">바로가기</a>&ensp;&ensp;{{ review_comment.content }}</p></li>
    {% endfor %}
  </ul>
  <hr>
  <ul class="list-group">
    <li class="list-group-item list-group-item-info">{{ person.username }}이 작성한 글</li>
    {% for talk in person.talkarticle_set.all %}
      <li class="list-group-item"><p class="my-2"><a href="{% url 'articles:talk_detail' talk.pk %}" class="badge badge-success">바로가기</a>&ensp;&ensp;{{ talk.title }}</p></li>
    {% endfor %}
  </ul>
  <hr>
  <ul class="list-group">
    <li class="list-group-item list-group-item-info">{{ person.username }}이 작성한 댓글</li>
    {% for talk_comment in person.talkcomment_set.all %}
      <li class="list-group-item"><p class="my-2"><a href="{% url 'articles:talk_detail' talk_comment.talk_article.pk %}" class="badge badge-success">바로가기</a>&ensp;&ensp;{{ talk_comment.content }}</p></li>
    {% endfor %}
  </ul>
  <hr>  


  {% comment %} <ul class="list-group">
    <li class="list-group-item list-group-item-primary">{{ person.username }}이 좋아요한 게시글</li>
    {% for review in person.like_review.all %}
      <li class="list-group-item"><p class="d-flex justify-content-between my-2">{{ review.title }}&ensp;<a href="{% url 'community:detail' review.pk %}" class="badge badge-success">Go</a></p></li>
    {% endfor %}
  </ul>
  <hr>
  <ul class="list-group mb-5">
    <li class="list-group-item list-group-item-danger">{{ person.username }}이 싫어요한 게시글</li>
    {% for review in person.unlike_review.all %}
      <li class="list-group-item"><p class="d-flex justify-content-between my-2">{{ review.title }}&ensp;<a href="{% url 'community:detail' review.pk %}" class="badge badge-success">Go</a></p></li>
    {% endfor %}
  </ul> {% endcomment %}
  

{% endblock %}

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
  <form action="" method="POST" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit">
        제출
      </button>
    {% endbuttons %}
  </form>
{% endblock %}

pjt/1학기 파이널 프로젝트 자료/민주 작업본/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
  <form action="{% url 'accounts:update' request.user.pk %}" method="POST" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit">
        수정
      </button>
    {% endbuttons %}
  </form>
  <form action="{% url 'accounts:delete' request.user.pk %}" method="POST" class="form">
    {% csrf_token %}
    <button type="submit">
      회원탈퇴
    </button>
  </form>
{% endblock %}